title: Prathima Kumari BV
logo: /assets/img/Photo.png

description:
 <p align="center">
  <a href="asset/Prathima-CV.pdf">Resume</a> |
  <a href="https://https://www.linkedin.com/in/prathima-kumari-bv/">LinkedIn</a> |
  <a href="https://github.com/PrathimaKumariBV">GitHub</a>
 </p> 
  <br>   
     Currently pursuing Advanced Certificate Program in Data Science, Machine Learning and Deep Learning in Upgrad.
     Successfully completed the <a href ="https://olympus1.mygreatlearning.com/course_certificate/QDOWBJJD">“Python Fundamentals for Beginners”</a> certification by Great Learning Academy.
     Attended Infosys Campus Connect Program on May 2012 and completed  successfully a batch on this program.
     Having 2 years experience as a lecturer.
     Worked at Asterix Technologies for 6 months to do academic project in internship.      
  <br>



theme: jekyll-theme-minimal
